#!/usr/bin/env python3
"""Emit the four-assertion host test for a SectionOverride policy case.

Every addition to aero::full_track::kPvsGatedExceptions must be guarded
by four asserts (track-artefact-diagnosis skill Phase 4a; tests/
test_full_track_policy.cpp is the canonical example):

    positive          : exact match returns true
    wrong-address     : same (track, zone), different DL -> false
    adjacent-zone     : same (track, dl), zone +- 1 -> false
    adjacent-track    : same (zone, dl), track +- 1 -> false

This tool takes the policy case (track, zone, dl) and emits the four
asserts to stdout (or to a target file). Forcing the four-assertion
discipline at the source -- instead of trusting the agent to remember
it -- caught every regression during the Bikini fix and avoids the
"passed because we only tested the positive case" trap.

Usage:
    python tools/rom/gen_policy_test.py --track 1 --zone 13 --dl 0x803903B8
    python tools/rom/gen_policy_test.py --track 1 --zone 13 --dl 0x803903B8 \\
        --append tests/test_full_track_policy.cpp

Use --header to also print the matching SectionOverride entry to paste
into src/aero_full_track_policy.h.
"""
import argparse
import sys
from pathlib import Path

# Distances for the wrong-address assertion. 4 bytes (one instruction word) off
# from the verified DL address -- the closest plausible alternative that no
# real DL can occupy while still being on the same 8-byte DL-alignment grid,
# so the assertion is meaningful (a typo of one hex digit would round to the
# same address; we want something a careless agent could plausibly ship).
WRONG_DL_OFFSET = 0x04
ADJ_ZONE_MAX = 63
ADJ_TRACK_MAX = 15


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--track", required=True, type=int, help="track id (0..15)")
    ap.add_argument("--zone", required=True, type=int, help="zone id (0..63)")
    ap.add_argument("--dl", required=True,
                    help="display-list vram address (0x80XXXXXX form)")
    ap.add_argument("--header", action="store_true",
                    help="also emit the SectionOverride line for the policy header")
    ap.add_argument("--append", default=None,
                    help="path to append the test block to (default: stdout)")
    ap.add_argument("--no-banner", action="store_true",
                    help="omit the comment header above the asserts")
    args = ap.parse_args()

    track = args.track
    zone = args.zone
    dl = int(args.dl, 16)
    if dl < 0x80000000:
        dl |= 0x80000000

    # Adjacent values: +/- 1 with the same lower-bound guards the agent
    # would have to think about anyway. We do the trivial bounds-checking
    # so an edge case (zone 0, zone 63, track 0) gets a meaningful
    # adjacent rather than a wraparound that always returns false.
    adj_zone = zone + 1 if zone < ADJ_ZONE_MAX else zone - 1
    adj_track = track + 1 if track < ADJ_TRACK_MAX else track - 1
    wrong_dl = (dl & 0xFFFFFFFC) | WRONG_DL_OFFSET

    lines = []
    if not args.no_banner:
        lines.append(f"    // Policy case: track={track} zone={zone} dl=0x{dl:08X}")
        lines.append(f"    // (generated by tools/rom/gen_policy_test.py)")
    lines.append(f"    assert(pvs_gated_section({track}u, {zone}u, 0x{dl:08X}u, 0x00u));"
                 f"          // positive")
    lines.append(f"    assert(!pvs_gated_section({track}u, {zone}u, 0x{wrong_dl:08X}u, 0x00u));"
                 f"         // wrong address")
    lines.append(f"    assert(!pvs_gated_section({track}u, {adj_zone}u, 0x{dl:08X}u, 0x00u));"
                 f"         // adjacent zone ({zone} -> {adj_zone})")
    lines.append(f"    assert(!pvs_gated_section({adj_track}u, {zone}u, 0x{dl:08X}u, 0x00u));"
                 f"         // adjacent track ({track} -> {adj_track})")

    if args.header:
        hdr = []
        if not args.no_banner:
            hdr.append(f"    // Policy case: track={track} zone={zone} dl=0x{dl:08X}")
            hdr.append(f"    // (generated by tools/rom/gen_policy_test.py)")
        hdr.append(f"    {{ {track}, {zone}, 0x{dl:08X}u }},  // <-- byte-verified DL")
        hdr_text = "\n".join(hdr)
        test_text = "\n".join(lines)

        out = (f"# === src/aero_full_track_policy.h ===\n"
               f"{hdr_text}\n\n"
               f"# === tests/test_full_track_policy.cpp ===\n"
               f"{test_text}\n")
    else:
        out = "\n".join(lines) + "\n"

    if args.append:
        p = Path(args.append)
        with p.open("a", encoding="utf-8") as f:
            f.write("\n" + out)
        print(f"# appended {len(lines)} assert lines to {p}", file=sys.stderr)
    else:
        sys.stdout.write(out)


if __name__ == "__main__":
    main()