"""Generate runtime mod guards for game functions changed by the port."""

import argparse
from pathlib import Path
import tomllib


def protected_addresses(config, symbols):
    """Return sorted VRAM addresses of stubbed or patched game functions."""
    addresses_by_name = {
        function["name"]: function["vram"]
        for section in symbols.get("section", [])
        for function in section.get("functions", [])
    }
    patch_config = config.get("patches", {})
    protected_names = set(patch_config.get("stubs", []))
    for patch_type in ("hook", "instruction"):
        protected_names.update(
            patch["func"] for patch in patch_config.get(patch_type, [])
        )

    missing = sorted(protected_names - addresses_by_name.keys())
    if missing:
        raise ValueError("patched functions missing from symbols: " + ", ".join(missing))
    return sorted(addresses_by_name[name] for name in protected_names)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("config", type=Path)
    parser.add_argument("symbols", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    with args.config.open("rb") as file:
        config = tomllib.load(file)
    with args.symbols.open("rb") as file:
        symbols = tomllib.load(file)

    addresses = protected_addresses(config, symbols)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    entries = ",\n".join(f"    0x{address:08X}u" for address in addresses)
    args.output.write_text(
        "// Generated by scripts/gen_mod_patch_guards.py; do not edit.\n"
        "static constexpr uint32_t protected_mod_functions[] = {\n"
        f"{entries}\n"
        "};\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
