// Headless boot probe for the ultramodern pivot (epic #54, phase #57).
//
// Links the whole-ROM recompiled image (RecompiledFuncs) against librecomp +
// ultramodern and boots the REAL entrypoint (0x80000400) under the modern
// runtime, with stubbed rsp/renderer callbacks and no RT64/SDL. Goal: confirm
// the recompiled boot reaches the first VI retrace and creates its first game
// thread (osCreateThread). A stall before that is a legitimate, characterised
// finding (run under gdb to capture the PC).
//
// Build/run (WSL): see recomp/CMakeLists.txt header.

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <memory>
#include <string>
#include <thread>

#include "librecomp/game.hpp"
#include "librecomp/rsp.hpp"
#include "ultramodern/ultramodern.hpp"
#include "ultramodern/events.hpp"
#include "ultramodern/error_handling.hpp"
#include "ultramodern/renderer_context.hpp"
#include "ultramodern/input.hpp"

#include <limits>

#include <SDL.h>          // RT64 default presenter (#58): real window + event pump under WSLg
#if defined(_WIN32)
#include <SDL_syswm.h>    // native Windows (#68): unwrap the HWND for ultramodern/RT64-D3D12
#endif
#include "aero_rt64.h"
#include "aero_audio.h"
#include "aero_config.h"
#include "aero_menu.h"
#include "aero_crash.h"   // issue #13 / A14
// ultramodern's native VI API (events.cpp), used by the promote_vi_context RT64 bridge.
extern "C" void osViSwapBuffer(uint8_t* rdram, int32_t frameBufPtr);
extern "C" void osViSetMode(uint8_t* rdram, int32_t mode_);

// Generated by N64Recomp (RecompiledFuncs/), the ROM-header entrypoint.
extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);

// Developer warp menu (#3, src/aero_warp.c): main/SDL thread publishes (F1-F6 hotkeys,
// AERO_WARP_AT probe), game thread consumes in aero_warp_tick.
extern "C" void aero_warp_request(int track0, int craft);

// Developer save-state (#17, src/aero_savestate.c): F7 snapshots guest RAM, F8 restores it.
// Main thread flips the request bit; the game thread does the copy at the next frame boundary.
extern "C" void aero_savestate_request_save(void);
extern "C" void aero_savestate_request_load(void);

// Our sibling TUs.
void register_overlays();
namespace headless {
std::unique_ptr<ultramodern::renderer::RendererContext>
create_render_context(uint8_t* rdram, ultramodern::renderer::WindowHandle window_handle, bool developer_mode);
int run_lighting_selftest();
}

// --- probe instrumentation ---------------------------------------------------
static std::atomic<int>  g_threads{0};
static std::atomic<int>  g_vis{0};
static std::atomic<bool> g_first_vi{false};
// Highest scene id (0x8013FF80, the scene manager's current-scene word) observed during
// the run. Lets a boot smoke run assert the boot cascade reaches the attract/race scenes
// (logo 0 -> attract 2 / title 3 -> menu 4 -> race 5) rather than just "didn't crash".
// See state_probe().
static std::atomic<int>  g_max_state{0};
static std::atomic<int>  g_swaps{0};

// AERO_CRASH_TEST: when set, the test thread's 2 s sleep must outlast
// boot_summary_and_exit() so its deliberate crash fires. Disable the VI cap.
static int quit_after_vis() {
    if (const char* e = std::getenv("AERO_MODERN_MAX_VIS")) {
        int v = std::atoi(e);
        if (v > 0) return v;
    }
    if (std::getenv("AERO_CRASH_TEST")) return std::numeric_limits<int>::max();
    return aero_rt64::enabled() ? std::numeric_limits<int>::max() : 120;
}
static const int kQuitAfterVis = quit_after_vis();

// Stall watchdog timeout. MUST exceed the wall-time the VI budget needs, or a raised
// AERO_MODERN_MAX_VIS is silently truncated by the watchdog before reaching the cap.
// Derive it from the cap (headless runs well above 10 VI/s, so cap/10 is generous) with
// a 30 s floor for the default boot. Uncapped play mode gets no watchdog (INT_MAX/10
// seconds is effectively never, and killing a live game window from a stall heuristic
// would be wrong anyway).
static int watchdog_seconds() {
    return std::max(30, kQuitAfterVis / 10 + 5);
}

// RDRAM base captured for the probes below (read-only sampling from the VI callback).
static uint8_t* g_aero_rdram = nullptr;

static void on_init_cb(uint8_t* rdram, recomp_context*) {
    g_aero_rdram = rdram;
    std::fprintf(stderr, "[probe] init complete; entering recomp_entrypoint @ 0x80000400\n");
}

static void thread_create_cb(uint8_t*, recomp_context*) {
    int n = ++g_threads;
    if (n <= 12) std::fprintf(stderr, "[probe] game thread #%d started (osCreateThread)\n", n);
}

// Print the one-line boot summary the runtime guard (tests/pivot/test_boot_smoke.py) parses,
// then terminate the process immediately. We _Exit instead of returning through
// recomp::start()'s teardown on purpose: that teardown joins the helper threads and munmaps
// RDRAM, but it does NOT terminate the 7 game osCreateThread threads -- once the main game
// thread actually runs its per-frame dispatch loop, those threads are live in native
// osRecvMesg and race the munmap into a SIGSEGV. This is a headless boot/probe harness that is
// quitting anyway, so skip the unwind and let process exit tear the game threads down.
// (Graceful game-thread shutdown is RT64-integration work, #58.)
[[noreturn]] static void boot_summary_and_exit() {
    std::fprintf(stderr, "[probe] boot summary; threads=%d vis=%d first_vi=%d max_state=%d swaps=%d\n",
                 g_threads.load(), g_vis.load(), (int)g_first_vi.load(), g_max_state.load(),
                 g_swaps.load());
    std::fflush(nullptr);
    std::_Exit(g_first_vi.load() ? 0 : 2);
}


// The Lamborghini stack carried a retrace-time __osViSwapContext bridge here
// (promote_vi_context): that ROM's osScheduler read the PRIVATE VI-manager globals
// __osViCurr/__osViNext directly, so the port had to emulate the VI interrupt's
// pointer promotion or the gfx-task gate latched shut after one frame.
//
// AeroGauge does NOT need it (verified 2026-07-11 by an all-.text immediate scan for
// its VI globals __osViCurr=0x80094C50 / __osViNext=0x80094C54, scratchpad globref.py):
// every reference lives inside libultra itself — the routed osVi* API bodies, the
// collapsed __osViInit (0x80077120), and the VI-ISR-only __osViSwapContext
// (0x80077FD0/0x800782F0), which never runs recompiled. Game code goes exclusively
// through the public osVi* entry points, all routed to ultramodern natives, so the
// native VI manager owns the whole swap path and there is no private state to mirror.

// Scene-manager progression tracker (PERMANENT harness instrumentation, not a throwaway
// diagnostic). AeroGauge's top-level state is its scene manager (derived 2026-07-12 by a
// ROM jump-table scan + live probing, see src/aero_warp.c for the full map): the per-frame
// driver func_80015C8C copies the requested scene 0x8013FF84 into the current scene
// 0x8013FF80 and jump-tables to the scene runner; 0x8013FF88 is the scene-local phase
// (race: 1 load -> 2 intro -> 3 playing; 6 = fresh entry; 7 = exit sequence) and
// 0x8013FF90 the race-parameter block (mode byte: 4 = menu race, 7 = attract demo).
// Scenes: 0/1 boot logo, 2 attract, 3 title, 4 menu, 5 race. We log every transition of
// (scene, request, phase, race-mode) and record the highest scene reached (g_max_state)
// so a run reports "stuck vs progressing" instead of just "didn't crash".
static void state_probe() {
    uint8_t* rdram = g_aero_rdram;
    if (rdram == nullptr) return;
    auto w32 = [&](uint32_t a) -> uint32_t {
        return *(uint32_t*)(rdram + ((a & ~3u) - 0x80000000u));
    };
    auto b8 = [&](uint32_t a) -> uint32_t {
        return (w32(a & ~3u) >> (24 - 8 * (a & 3u))) & 0xFF;
    };
    uint32_t scene = w32(0x8013FF80), req = w32(0x8013FF84);
    uint32_t phase = w32(0x8013FF88), mode = b8(0x8013FF90);
    static uint32_t last[4] = { ~0u, ~0u, ~0u, ~0u };
    if (scene != last[0] || req != last[1] || phase != last[2] || mode != last[3]) {
        std::fprintf(stderr, "[state] vi=%d  scene=%u req=%u phase=%u race_mode=%u\n",
                     g_vis.load(), scene, req, phase, mode);
        last[0] = scene; last[1] = req; last[2] = phase; last[3] = mode;
    }
    if ((int)scene > g_max_state.load() && scene < 64) g_max_state.store((int)scene);
}

// Menu-screen probe (PERMANENT harness instrumentation, same class as state_probe): samples the
// menu overlay's current-screen id D_80098562 (set by the "request menu screen" API func_800383A8,
// docs/notes/menu.md) plus its neighbour D_80098560 each VI and logs transitions -- the menu chain
// (players/mode/series/car/name/pak-message, #69) all runs under top-level state 6, so state_probe
// alone cannot show menu navigation.
static void menu_probe() {
    // TODO(aerogauge): D_80098562/D_80098560 are LAMBORGHINI menu globals; disabled.
    return;
}

// Frame-pace probe (PERMANENT harness instrumentation, same class as state_probe): counts game
// framebuffer swaps by watching ultramodern's native VI_ORIGIN register once per VI. AeroGauge's
// swap path is fully native (osViSwapBuffer routed; no private VI state, see the note above), so
// the ROM-global sampling the Lambo port used does not apply — the native register IS the ground
// truth the VI scanout would read. At most one swap can become current per retrace, so per-VI
// sampling cannot miss one. ~0.5 swaps/VI is a 30 fps title on a 60 Hz VI; ~1.0 swaps/VI means
// the port runs the game 2x fast (pacing bug class).
static void pace_probe(int vi_n) {
    static uint32_t s_last_origin = 0;
    const ultramodern::renderer::ViRegs* vr = ultramodern::renderer::get_vi_regs();
    if (vr == nullptr) return;
    uint32_t origin = vr->VI_ORIGIN_REG;
    if (origin != s_last_origin) {
        s_last_origin = origin;
        int s = ++g_swaps;
        // The periodic (s % 256, ~8.5 s) line is gated behind AERO_HARNESS_LOG: it runs
        // on the VI thread -- the game's master pacer -- and a synchronous console write
        // here stalls pacing itself (same hitch class as the gfx-thread heartbeat, see
        // rt64_renderer.cpp). The first-8-swaps boot lines are one-time and stay.
        if (s <= 8 || (aero::config::harness_log() && (s % 256) == 0))
            std::fprintf(stderr, "[probe] fb swap #%d -> VI_ORIGIN=0x%08x (vi=%d)\n",
                         s, origin, vi_n);
    }
}

// Provided by runtime patch 0001 (mesgqueue.cpp), gated by LAMBO_THREAD_TRACE — the lambo_
// prefix stays because the symbol lives inside the patched N64ModernRuntime submodule.
extern "C" void lambo_thread_trace_dump(int vi);
// Scripted warp trigger (PERMANENT harness instrumentation, same class as state_probe):
// AERO_WARP_AT=vi:track[:craft] (track/craft 1-based, like AERO_WARP) publishes a warp
// request at the given VI from this main-thread callback — the same cross-thread path the
// F1-F6 hotkeys use — so headless runs can exercise mid-run and mid-race re-warps.
static void warp_at_probe(int vi_n) {
    static int at = -1, track = 0, craft = 0;
    if (at == -1) {
        at = 0;
        if (const char* e = std::getenv("AERO_WARP_AT")) {
            if (std::sscanf(e, "%d:%d:%d", &at, &track, &craft) < 2 || track < 1 || track > 6) {
                std::fprintf(stderr, "[warp] AERO_WARP_AT=%s invalid: vi:track[:craft]\n", e);
                at = 0;
            }
        }
    }
    if (at > 0 && vi_n == at) aero_warp_request(track - 1, craft - 1);
}

// VI-thread pacing probe (PERMANENT harness instrumentation, companion to the gfx-thread
// probe in rt64_renderer.cpp; enabled by the same AERO_FRAME_LOG=<path>, writing to
// <path>.vi): vi_cb runs once per VI tick on ultramodern's VI thread, so a gap here means
// the PACER stalled (Sleep granularity / timer / message-queue / console-lock contention),
// as opposed to a gfx-thread stall. Lines are tagged [vi-pace] vs the gfx probe's [gfx-pace].
static void vi_pace_probe() {
    static FILE* f = aero::config::open_frame_log(".vi");
    if (f == nullptr) return;
    using clock = std::chrono::steady_clock;
    static const auto t0 = clock::now();
    static clock::time_point last{};
    const auto now = clock::now();
    if (last.time_since_epoch().count() != 0) {
        double gap = std::chrono::duration<double, std::milli>(now - last).count();
        if (gap > 25.0) {
            std::fprintf(f, "[vi-pace] t=%.1f VI tick gap=%.2fms\n",
                         std::chrono::duration<double, std::milli>(now - t0).count(), gap);
            std::fflush(f);
        }
    }
    last = now;
}

static void vi_cb() {
    vi_pace_probe();
    state_probe();
    menu_probe();
    int n = ++g_vis;
    warp_at_probe(n);
    pace_probe(n);
    if ((n % 50) == 0) lambo_thread_trace_dump(n); // THROWAWAY: per-thread recv/send snapshot to find the frozen thread
    if (!g_first_vi.exchange(true)) std::fprintf(stderr, "[probe] FIRST VI retrace\n");
    if (n == kQuitAfterVis) {
        std::fprintf(stderr, "[probe] reached %d VIs; quitting\n", n);
        boot_summary_and_exit();
    }
}

// RSPRecomp'd aspMain (#53): the M_AUDTASK audio microcode. Generation +
// static-bytes ROM 0x7F330 derivation are documented in `aspMain.us.toml`.
RspExitReason aspMain(uint8_t* rdram, uint32_t ucode_addr);

static RspUcodeFunc* get_rsp_microcode_stub(const OSTask* task) {
    if (task->t.type == 2) return aspMain; // M_AUDTASK: RSPRecomp'd real synthesis (#53)
    static std::atomic<bool> logged{false};
    if (!logged.exchange(true))
        std::fprintf(stderr, "[probe] get_rsp_microcode: unhandled task type %u -> nullptr\n",
                     (unsigned)task->t.type);
    return nullptr;
}

static void message_box_stub(const char* msg) {
    std::fprintf(stderr, "[probe] message_box: %s\n", msg);
}

// Input (#68) — defined below in the input section; used by the window/pump callbacks above them.
static void input_sample();
static void input_open_controller(int joystick_index);
static void input_close_controller(SDL_JoystickID which);
static void rumble_apply();  // rumble-pak sink (#69); defined in the input section below

static void toggle_fullscreen() {
    aero::menu::toggle_fullscreen();
}

static ultramodern::renderer::WindowHandle create_window_stub(void* /*gfx_data*/) {
    // RT64 default presenter (#58): RT64 needs a real window with a Vulkan surface
    // (Linux). Created on the main thread; the SDL event pump runs in update_gfx_stub
    // below (also main thread, via recomp::start's loop). AERO_HEADLESS=1 (harness
    // knob) skips the window entirely; SDL failure degrades to headless the same way.
    if (aero_rt64::enabled()) {
        // Enable SDL2's native Steam Controller HIDAPI driver (original Steam Controller); newer
        // pads (incl. Steam Controller Gen2 via Steam Input) present as a standard XInput gamepad
        // that the SDL_GameController API handles without this hint. Must precede SDL init.
        SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI_STEAM, "1");
        // Keep controller events flowing even when the window loses focus (matches the reference
        // ports; otherwise held inputs freeze on alt-tab).
        SDL_SetHint(SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS, "1");
        // GAMECONTROLLER pulls in JOYSTICK + enables CONTROLLERDEVICEADDED/REMOVED events (#68).
        if (SDL_InitSubSystem(SDL_INIT_VIDEO | SDL_INIT_GAMECONTROLLER) != 0) {
            std::fprintf(stderr, "[rt64] SDL_InitSubSystem(VIDEO|GAMECONTROLLER) failed: %s -- staying headless\n",
                         SDL_GetError());
            return ultramodern::renderer::WindowHandle{};
        }
        // Open any controller already connected at launch (ADDED events are also queued, but this
        // covers pads present before the event pump starts).
        for (int i = 0; i < SDL_NumJoysticks(); i++) input_open_controller(i);
        uint32_t flags = SDL_WINDOW_RESIZABLE;
#if defined(__linux__)
        flags |= SDL_WINDOW_VULKAN;
#endif
        // Window size + startup fullscreen come from graphics.json (loaded in main()
        // before recomp::start). Fullscreen is owned by SDL on this (main) thread --
        // see the F11 handler in update_gfx_stub.
        const aero::config::WindowSize win_size = aero::config::window_size();
        if (ultramodern::renderer::get_graphics_config().wm_option ==
            ultramodern::renderer::WindowMode::Fullscreen) {
            flags |= SDL_WINDOW_FULLSCREEN_DESKTOP;
        }
        SDL_Window* window = SDL_CreateWindow("AeroGauge",
                                              SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                                              win_size.width, win_size.height, flags);
        if (window == nullptr) {
            std::fprintf(stderr, "[rt64] SDL_CreateWindow failed: %s -- staying headless\n",
                         SDL_GetError());
            return ultramodern::renderer::WindowHandle{};
        }
        aero::menu::attach(window);
#if defined(__linux__)
        std::fprintf(stderr, "[rt64] SDL window created (%dx%d, Vulkan surface)\n",
                     win_size.width, win_size.height);
        return ultramodern::renderer::WindowHandle{window};
#elif defined(_WIN32)
        // Native Windows (#68): ultramodern's WindowHandle is {HWND, thread_id} and RT64
        // drives its D3D12 swapchain off the raw HWND, so unwrap it from the SDL window.
        // Same shape as Zelda64Recomp's Windows path (SDL_SysWMinfo -> info.win.window).
        SDL_SysWMinfo wmInfo;
        SDL_VERSION(&wmInfo.version);
        if (SDL_GetWindowWMInfo(window, &wmInfo) != SDL_TRUE) {
            std::fprintf(stderr, "[rt64] SDL_GetWindowWMInfo failed: %s -- staying headless\n",
                         SDL_GetError());
            SDL_DestroyWindow(window);
            return ultramodern::renderer::WindowHandle{};
        }
        std::fprintf(stderr, "[rt64] SDL window created (%dx%d, Win32 HWND -> D3D12)\n",
                     win_size.width, win_size.height);
        return ultramodern::renderer::WindowHandle{wmInfo.info.win.window, GetCurrentThreadId()};
#else
        std::fprintf(stderr, "[rt64] window handle wiring not implemented on this platform\n");
        SDL_DestroyWindow(window);
        return ultramodern::renderer::WindowHandle{};
#endif
    }
    return ultramodern::renderer::WindowHandle{}; // headless: null handle
}

static void update_gfx_stub(void* /*gfx_data*/) {
    // Pump SDL events on the main thread so the RT64 window stays responsive under WSLg.
    if (aero_rt64::enabled()) {
        SDL_Event event;
        while (SDL_PollEvent(&event)) {
            // Play mode has no VI cap (see quit_after_vis), so closing the window is the
            // quit path: reuse the summary+_Exit teardown (game threads are torn down by
            // process exit; see boot_summary_and_exit's rationale).
            if (event.type == SDL_QUIT ||
                (event.type == SDL_WINDOWEVENT && event.window.event == SDL_WINDOWEVENT_CLOSE)) {
                std::fprintf(stderr, "[probe] window closed; quitting\n");
                boot_summary_and_exit();
            }
            else if (aero::menu::handle_event(event)) {
                continue;
            }
            else if (event.type == SDL_KEYDOWN && !event.key.repeat &&
                     (event.key.keysym.sym == SDLK_F11 ||
                      (event.key.keysym.sym == SDLK_RETURN && (event.key.keysym.mod & KMOD_ALT)))) {
                toggle_fullscreen();
            }
            else if (event.type == SDL_CONTROLLERDEVICEADDED) {
                input_open_controller(event.cdevice.which);   // which = joystick index (ADDED)
            }
            else if (event.type == SDL_CONTROLLERDEVICEREMOVED) {
                input_close_controller(event.cdevice.which);  // which = instance id (REMOVED)
            }
        }
        // SDL_PollEvent pumped events above (implicitly SDL_GameControllerUpdate); sample the
        // fresh keyboard+pad state into the atomic snapshot the game thread reads via get_input.
        input_sample();
        // Apply the game thread's latest rumble-pak motor state to the physical pad (#69).
        rumble_apply();
    }
}

// --- input (#68) --------------------------------------------------------------------------
// Real SDL2 keyboard + gamepad -> N64 OSContPad, feeding ultramodern's get_input callback
// (which packs our button mask + float stick into OSContPad via osContGetReadData).
//
// Threading: SDL events pump on the MAIN thread (update_gfx_stub); get_input/poll_input are
// called on the GAME thread (osContStartReadData). So the main thread SAMPLES SDL state into
// one atomic snapshot each frame (input_sample()), and the game thread only READS the
// snapshot -- no cross-thread SDL calls, no lock. Snapshot layout (uint32_t):
//   [15:0] = N64 button mask, [23:16] = stick_x (int8), [31:24] = stick_y (int8).
//
// Port 0 is reported connected UNCONDITIONALLY (input_device_info below) even with no physical
// pad: the keyboard is a valid input device, and the ROM's object-slot gate (func_8007A8A0)
// bails to a stuck state 6 unless port 0 reads as present (#64/#53).
//
// AERO_MODERN_INPUT (env, hex OS_CONT mask) is OR'd into every read -- the permanent harness
// knob for headless title-advance scripting (AERO_HEADLESS never inits SDL gamecontroller, so
// its snapshot stays 0 and get_input returns exactly the env mask, as before this change).

// N64 OSContPad button bits (libultra ultra64/controller.h; standard across all N64 titles).
enum {
    N64_A       = 0x8000, N64_B      = 0x4000, N64_Z     = 0x2000, N64_START = 0x1000,
    N64_DU      = 0x0800, N64_DD     = 0x0400, N64_DL    = 0x0200, N64_DR    = 0x0100,
    N64_L       = 0x0020, N64_R      = 0x0010,
    N64_CU      = 0x0008, N64_CD     = 0x0004, N64_CL    = 0x0002, N64_CR    = 0x0001,
};

// N64 hardware stick maxes at roughly +-80 after calibration; games are tuned for that range,
// so we scale full deflection to +-80 (faithfulness) rather than the full int8 +-127.
static constexpr int   N64_STICK_MAX   = 80;
static constexpr int   PAD_AXIS_DEADZONE = 8000;   // ~24% of int16 range (SDL recommended ~8000)
static constexpr int   PAD_TRIG_THRESH   = 8000;   // analog trigger -> digital
static constexpr int   PAD_CSTICK_THRESH = 12000;  // right-stick -> C-buttons

static uint16_t g_held_buttons = 0;                 // AERO_MODERN_INPUT env override, OR'd in
static int8_t   g_held_sx = 0, g_held_sy = 0;       // AERO_MODERN_INPUT stick override (harness)
// AERO_INPUT_PULSE=BTNHEX:PERIOD:DUTY[:STARTVI] -- periodic button pulse for headless menu
// navigation (a held AERO_MODERN_INPUT mask is one EDGE forever, so it can advance at most one
// menu; a pulse presses/releases every PERIOD VIs for DUTY VIs, walking a whole menu chain).
static uint16_t g_pulse_buttons = 0;
static int      g_pulse_period = 0, g_pulse_duty = 0, g_pulse_start = 0;
static int      g_pulse_count = 0;   // optional 5th field: stop after N pulses (0 = unlimited)
static std::atomic<uint32_t> g_input_snapshot{0};   // main-thread sampled, game-thread read
static SDL_GameController* g_pad = nullptr;          // first opened controller (port 0)

// --- rumble-pak sink (#69) ----------------------------------------------------------------
// The game's SI/PIF bridge (func_8007F780 -> aero_joybus_answer, recomp/src/libultra_stubs.c)
// runs on the GAME thread and decodes the ROM's motor-control pak writes (joybus cmd 0x03 to
// pak block 0xC000: payload 0x01 = motor on, 0x00 = off). SDL rumble must be driven from the
// MAIN thread (that owns g_pad open/close), so -- exactly like input -- the game thread only
// PUBLISHES an atomic request and the main-thread pump (update_gfx_stub) applies it. Declared
// extern "C" so the C responder in libultra_stubs.c can call aero_pak_set_rumble().
static std::atomic<int> g_rumble_on{0};              // game-thread write, main-thread read
extern "C" void aero_pak_set_rumble(int on) { g_rumble_on.store(on ? 1 : 0, std::memory_order_relaxed); }

// (The Lamborghini port's developer warp menu / save-state hooks were dropped from the
// base stack — they were built around that game's specific state layout. Re-grow
// AeroGauge equivalents once its state machine is mapped.)

// Apply the published rumble state to the physical pad. Called once per main-thread pump.
// N64 rumble is bang-bang (motor fully on or off), so map to SDL full strength. We refresh the
// effect every pump with a short expiry (150 ms > one 30 fps frame) so a sustained motor-on
// keeps buzzing without needing a re-trigger, and a single motor-off (or a dropped controller)
// lets it lapse. Idempotent-ish: we only issue an SDL call on an on/off EDGE plus periodic
// refresh while on, to avoid hammering the HID layer every frame.
static void rumble_apply() {
    static int last = 0;
    int on = g_rumble_on.load(std::memory_order_relaxed);
    if (g_pad == nullptr || !SDL_GameControllerGetAttached(g_pad)) { last = 0; return; }
    if (on) {
        SDL_GameControllerRumble(g_pad, 0xFFFF, 0xFFFF, 150);   // refresh; expiry > frame time
    } else if (last) {
        SDL_GameControllerRumble(g_pad, 0, 0, 0);               // off edge: stop immediately
    }
    last = on;
}

static int8_t pad_axis_to_n64(int v) {              // int16 SDL axis -> int8 N64 stick (deadzoned)
    if (v > -PAD_AXIS_DEADZONE && v < PAD_AXIS_DEADZONE) return 0;
    float f = v / 32767.0f;
    if (f >  1.0f) f =  1.0f;
    if (f < -1.0f) f = -1.0f;
    return (int8_t)(f * N64_STICK_MAX);
}

// Sample SDL keyboard + gamepad on the MAIN thread and publish the atomic snapshot.
static void input_sample() {
    uint16_t b = 0;
    int sx = 0, sy = 0;

    if (g_pad != nullptr && SDL_GameControllerGetAttached(g_pad)) {
        auto down = [](SDL_GameControllerButton g) { return SDL_GameControllerGetButton(g_pad, g) != 0; };
        // Mapping is tuned to THIS game's VERIFIED menu control scheme (not the generic
        // Zelda64Recomp default): the ROM's menu driver (func_800030F8) confirms on A|START
        // (andi 0x9000), cancels on B (0x4000), and moves the cursor with the ANALOG STICK only
        // -- it tests no C-button or D-pad bit for menu nav. So the face buttons follow Xbox-native
        // intent: A=confirm, B=cancel. The C-buttons live on X/Y + the right stick, where this
        // game's menus never look at them, so they can't produce phantom menu input.
        // NOTE: the *in-race* meaning of each N64 bit (throttle/brake/camera) is NOT yet ROM-verified
        // -- the race-overlay input consumer hasn't been read. This is a physical Xbox->N64 binding,
        // not a claim about race behaviour; revisit when state 8 becomes playable (see race.md).
        if (down(SDL_CONTROLLER_BUTTON_A))             b |= N64_A;      // confirm (menu)
        if (down(SDL_CONTROLLER_BUTTON_B))             b |= N64_B;      // cancel (menu)
        if (down(SDL_CONTROLLER_BUTTON_X))             b |= N64_CL;     // West  -> C-left
        if (down(SDL_CONTROLLER_BUTTON_Y))             b |= N64_CU;     // North -> C-up
        if (down(SDL_CONTROLLER_BUTTON_START))         b |= N64_START;  // advance / pause
        if (down(SDL_CONTROLLER_BUTTON_LEFTSHOULDER))  b |= N64_L;
        if (down(SDL_CONTROLLER_BUTTON_RIGHTSHOULDER)) b |= N64_R;
        if (down(SDL_CONTROLLER_BUTTON_DPAD_UP))        b |= N64_DU;
        if (down(SDL_CONTROLLER_BUTTON_DPAD_DOWN))      b |= N64_DD;
        if (down(SDL_CONTROLLER_BUTTON_DPAD_LEFT))      b |= N64_DL;
        if (down(SDL_CONTROLLER_BUTTON_DPAD_RIGHT))     b |= N64_DR;
        // N64 Z on the left analog trigger (LT); N64 R also on the right trigger (RT) for racing feel.
        if (SDL_GameControllerGetAxis(g_pad, SDL_CONTROLLER_AXIS_TRIGGERLEFT)  > PAD_TRIG_THRESH) b |= N64_Z;
        if (SDL_GameControllerGetAxis(g_pad, SDL_CONTROLLER_AXIS_TRIGGERRIGHT) > PAD_TRIG_THRESH) b |= N64_R;
        // Remaining C directions: right-stick click -> C-down; the right stick itself -> all four C's.
        if (down(SDL_CONTROLLER_BUTTON_RIGHTSTICK))     b |= N64_CD;    // right-stick click
        int rx = SDL_GameControllerGetAxis(g_pad, SDL_CONTROLLER_AXIS_RIGHTX);
        int ry = SDL_GameControllerGetAxis(g_pad, SDL_CONTROLLER_AXIS_RIGHTY);
        if (rx >  PAD_CSTICK_THRESH) b |= N64_CR;
        if (rx < -PAD_CSTICK_THRESH) b |= N64_CL;
        if (ry >  PAD_CSTICK_THRESH) b |= N64_CD;
        if (ry < -PAD_CSTICK_THRESH) b |= N64_CU;
        // Left analog stick -> N64 stick (SDL Y is +down, N64 stick_y is +up -> negate).
        sx =  pad_axis_to_n64(SDL_GameControllerGetAxis(g_pad, SDL_CONTROLLER_AXIS_LEFTX));
        sy = -pad_axis_to_n64(SDL_GameControllerGetAxis(g_pad, SDL_CONTROLLER_AXIS_LEFTY));
    }

    // Keyboard fallback (always sampled; OR'd with the pad). Arrow keys steer; racing essentials
    // on the left hand. Digital keys drive the stick to full deflection only if the pad is idle.
    if (const Uint8* ks = SDL_GetKeyboardState(nullptr)) {
        if (ks[SDL_SCANCODE_X])      b |= N64_A;       // accelerate / confirm
        if (ks[SDL_SCANCODE_C])      b |= N64_B;       // brake / cancel
        if (ks[SDL_SCANCODE_Z])      b |= N64_Z;
        if (ks[SDL_SCANCODE_RETURN]) b |= N64_START;
        if (ks[SDL_SCANCODE_Q])      b |= N64_L;
        if (ks[SDL_SCANCODE_E])      b |= N64_R;
        if (ks[SDL_SCANCODE_I])      b |= N64_CU;
        if (ks[SDL_SCANCODE_K])      b |= N64_CD;
        if (ks[SDL_SCANCODE_J])      b |= N64_CL;
        if (ks[SDL_SCANCODE_L])      b |= N64_CR;
        int kx = 0, ky = 0;
        if (ks[SDL_SCANCODE_LEFT]  || ks[SDL_SCANCODE_A]) kx -= N64_STICK_MAX;
        if (ks[SDL_SCANCODE_RIGHT] || ks[SDL_SCANCODE_D]) kx += N64_STICK_MAX;
        if (ks[SDL_SCANCODE_UP]    || ks[SDL_SCANCODE_W]) ky += N64_STICK_MAX;
        if (ks[SDL_SCANCODE_DOWN]  || ks[SDL_SCANCODE_S]) ky -= N64_STICK_MAX;
        if (sx == 0 && kx != 0) sx = kx;               // pad stick wins if deflected
        if (sy == 0 && ky != 0) sy = ky;

        // Developer warp menu (#3, src/aero_warp.c): F1..F6 warp straight to that track.
        // Edge-triggered here on the SDL thread; consumed by aero_warp_tick on the game
        // thread (hooked at the scene-manager tick func_80015FD0).
        static Uint8 warp_prev[6] = {};
        for (int i = 0; i < 6; i++) {
            Uint8 down = ks[SDL_SCANCODE_F1 + i];
            if (down && !warp_prev[i]) aero_warp_request(i, -1);
            warp_prev[i] = down;
        }

        // Developer save-state (#17): F7 saves the current guest RAM to the state slot,
        // F8 restores it (F1-F6 are the warp keys above). Edge-detected here (main thread);
        // the copy runs on the game thread at the next frame boundary (src/aero_savestate.c).
        static Uint8 f7_prev = 0, f8_prev = 0;
        Uint8 f7 = ks[SDL_SCANCODE_F7], f8 = ks[SDL_SCANCODE_F8];
        if (f7 && !f7_prev) aero_savestate_request_save();
        if (f8 && !f8_prev) aero_savestate_request_load();
        f7_prev = f7; f8_prev = f8;
    }

    uint32_t snap = (uint16_t)b
                  | ((uint32_t)(uint8_t)(int8_t)sx << 16)
                  | ((uint32_t)(uint8_t)(int8_t)sy << 24);
    g_input_snapshot.store(snap, std::memory_order_relaxed);
}

// Open the first connected game controller into port 0 (idempotent; called at init + on hotplug).
static void input_open_controller(int joystick_index) {
    if (g_pad != nullptr) return;
    if (!SDL_IsGameController(joystick_index)) return;
    g_pad = SDL_GameControllerOpen(joystick_index);
    if (g_pad != nullptr)
        std::fprintf(stderr, "[input] controller connected: %s\n",
                     SDL_GameControllerName(g_pad) ? SDL_GameControllerName(g_pad) : "(unknown)");
}
static void input_close_controller(SDL_JoystickID which) {
    if (g_pad == nullptr) return;
    SDL_Joystick* js = SDL_GameControllerGetJoystick(g_pad);
    if (js != nullptr && SDL_JoystickInstanceID(js) == which) {
        SDL_GameControllerClose(g_pad);
        g_pad = nullptr;
        std::fprintf(stderr, "[input] controller disconnected\n");
    }
}

static void input_poll_stub() {}
static bool input_get_input(int controller_num, uint16_t* buttons, float* x, float* y) {
    if (controller_num != 0) return false;
    uint32_t snap = g_input_snapshot.load(std::memory_order_relaxed);
    uint16_t b  = (uint16_t)(snap & 0xFFFF) | g_held_buttons;   // env mask always OR'd (harness knob)
    if (g_pulse_period > 0) {                                   // scripted pulse (harness knob)
        int vi = g_vis.load(std::memory_order_relaxed);
        if (vi >= g_pulse_start && ((vi - g_pulse_start) % g_pulse_period) < g_pulse_duty
            && (g_pulse_count == 0 || (vi - g_pulse_start) / g_pulse_period < g_pulse_count))
            b |= g_pulse_buttons;
    }
    int8_t   sx = (int8_t)((snap >> 16) & 0xFF);
    int8_t   sy = (int8_t)((snap >> 24) & 0xFF);
    if (sx == 0) sx = g_held_sx;                                // env stick fills in when live stick idle
    if (sy == 0) sy = g_held_sy;
    if (buttons) *buttons = b;
    // ultramodern does stick_x = (int8_t)(127 * x), so divide by 127 (NOT N64_STICK_MAX) to
    // preserve our authentic +-80 range through that re-scale instead of re-expanding to +-127.
    if (x) *x = sx / 127.0f;
    if (y) *y = sy / 127.0f;
    return true;
}
static ultramodern::input::connected_device_info_t input_device_info(int controller_num) {
    using namespace ultramodern::input;
    if (controller_num == 0) return { Device::Controller, Pak::None };
    return { Device::None, Pak::None };
}

int main(int argc, char** argv) {
    // Deterministic lighting self-test: no ROM, no runtime -- exercises the swrender
    // light-decode + lambert path on a synthetic DL and exits (tests/pivot/test_lighting.py).
    if (std::getenv("AERO_LIGHTING_SELFTEST")) {
        return headless::run_lighting_selftest();
    }
    const char* rom_path = (argc > 1) ? argv[1] : "AeroGauge (USA).z64";
    std::fprintf(stderr, "[probe] ROM: %s\n", rom_path);

    register_overlays();
    // After register_overlays so the native-ptr -> vram map is already wired.
    aero::crash::install();

    // Smoke-test the handler: AERO_CRASH_TEST=<reason> schedules a 2 s
    // sleep then a deliberate crash so the dump format can be verified in
    // CI / field testing without waiting for a real bug.
    if (const char* ct = std::getenv("AERO_CRASH_TEST")) {
        std::fprintf(stderr, "[probe] AERO_CRASH_TEST=%s; injecting deliberate crash in 2s\n", ct);
        std::thread([](const char* reason){
            std::this_thread::sleep_for(std::chrono::seconds(2));
            aero::crash::record_recent(0x80001CD0u, 0x800024F8u);  // func_800028D0 entry, $ra into menu driver
            aero::crash::record_recent(0x80000450u, 0);            // BootMain entry
            aero::crash::crash_dump_and_die(reason);
        }, ct).detach();
    }

    // Load + apply graphics.json BEFORE recomp::start: ultramodern latches the config
    // and the RT64 context constructor reads it via get_graphics_config(). This is the
    // whole user-facing options mechanism (edit the file; F11 toggles fullscreen live).
    aero::config::load_and_apply_graphics();

    // librecomp's config path is where game SAVES (EEPROM/SRAM/pak) and mod config
    // live -- point it at the same persistent per-user directory as graphics.json.
    // (It was a throwaway temp dir during the headless-probe era, which silently
    // discarded saves on temp cleanup.)
    std::filesystem::path config_dir = aero::config::app_config_dir();
    std::filesystem::create_directories(config_dir);
    recomp::register_config_path(config_dir);

    recomp::GameEntry game{};
    game.rom_hash          = 0x89ea0690f3e22201ULL; // XXH3_64(big-endian .z64, 8 MiB)
    game.internal_name     = "AEROGAUGE           "; // ROM header name @0x20 (20 bytes)
    game.game_id           = u8"aerogauge.us";
    game.is_enabled        = true;
    // 4Kbit EEPROM (512 B): the ROM's save loader (0x80061D00) probes with osEepromProbe and
    // the routed librecomp eep.cpp natives gate on this via recomp::eeprom_allowed(). The
    // probe status bits in __osEepStatus map 0x8000 -> type 1 (4K), which is what this
    // cartridge shipped with.
    game.save_type         = recomp::SaveType::Eep4k;
    game.entrypoint_address = (gpr)(int32_t)0x80000400u;
    game.entrypoint        = recomp_entrypoint;
    game.on_init_callback  = on_init_cb;
    game.thread_create_callback = thread_create_cb;
    recomp::register_game(game);

    std::u8string game_id = u8"aerogauge.us";
    recomp::RomValidationError verr = recomp::select_rom(rom_path, game_id);
    if (verr != recomp::RomValidationError::Good) {
        std::fprintf(stderr, "[probe] select_rom FAILED (RomValidationError=%d)\n", (int)verr);
        return 1;
    }
    std::fprintf(stderr, "[probe] ROM validated; rom_hash matches\n");

    // recomp::start() blocks the calling thread until ultramodern::quit(), so
    // kick the game off from a side thread once the runtime has set up.
    std::thread starter([game_id]() {
        std::this_thread::sleep_for(std::chrono::milliseconds(150));
        std::fprintf(stderr, "[probe] calling start_game\n");
        std::u8string gid = game_id;
        recomp::start_game(gid);
    });
    starter.detach();

    // Watchdog: guarantee the probe terminates and reports, even on a stall.
    const int wd_sec = watchdog_seconds();
    std::thread watchdog([wd_sec]() {
        std::this_thread::sleep_for(std::chrono::seconds(wd_sec));
        std::fprintf(stderr, "[probe] WATCHDOG %ds: threads=%d vis=%d first_vi=%d\n",
                     wd_sec, g_threads.load(), g_vis.load(), (int)g_first_vi.load());
        // Exit deterministically (same as the VI-cap path) rather than ultramodern::quit(),
        // whose teardown munmaps RDRAM out from under the live game threads (SIGSEGV race).
        boot_summary_and_exit();
    });
    watchdog.detach();

    recomp::Configuration cfg{};
    cfg.project_version = recomp::Version{1, 0, 0, std::string{}};
    cfg.rsp_callbacks.get_rsp_microcode = get_rsp_microcode_stub;
    cfg.renderer_callbacks.create_render_context = headless::create_render_context;
    cfg.gfx_callbacks.create_window = create_window_stub; // avoids start()'s no-window assert
    cfg.gfx_callbacks.update_gfx = update_gfx_stub;       // SDL event pump when RT64 is active
    cfg.events_callbacks.vi_callback = vi_cb;
    cfg.error_handling_callbacks.message_box = message_box_stub;
    // window_handle left default-empty -> create_window_stub() is used.

    // Controller 0 is wired by DEFAULT (carried over from the Lamborghini port's
    // controller-gating issue). AeroGauge's equivalent SI read path is not yet
    // identified — see TODO(aerogauge) on libultra_stubs.c funcs near func_80075C60 —
    // so the rationale above (D_8011C681 count, object-slot gate func_8007A8A0) does
    // not necessarily apply here; this is the safe default of "controller 0 connected"
    // and we revalidate once the port's SI signal path is mapped.
    // AERO_MODERN_INPUT still overrides the held-button mask for input testing (e.g. =1000 holds
    // START); default (unset) = controller 0 connected, no buttons held.
    if (const char* in = std::getenv("AERO_MODERN_INPUT")) {
        // Format: BTNHEX[:SX[:SY]]. OS_CONT bits: START=0x1000, A=0x8000, B=0x4000; SX/SY are
        // signed decimal stick values. e.g. AERO_MODERN_INPUT=1000 holds START;
        // AERO_MODERN_INPUT=0:53:0 holds the stick at x=+53 with no buttons.
        char* end = nullptr;
        g_held_buttons = (uint16_t)std::strtoul(in, &end, 16);
        if (end != nullptr && *end == ':') {
            g_held_sx = (int8_t)std::strtol(end + 1, &end, 10);
            if (end != nullptr && *end == ':') {
                g_held_sy = (int8_t)std::strtol(end + 1, nullptr, 10);
            }
        }
    }
    if (const char* pu = std::getenv("AERO_INPUT_PULSE")) {
        // BTNHEX:PERIOD:DUTY[:STARTVI[:COUNT]], VI units. e.g. 1000:150:4:300 taps START for 4 VIs
        // every 150 VIs starting at VI 300 -- enough edges to walk the whole menu chain headless.
        // COUNT stops after N taps (0/absent = unlimited) so a walk can PARK on a target screen.
        char* end = nullptr;
        g_pulse_buttons = (uint16_t)std::strtoul(pu, &end, 16);
        if (end && *end == ':') g_pulse_period = (int)std::strtol(end + 1, &end, 10);
        if (end && *end == ':') g_pulse_duty   = (int)std::strtol(end + 1, &end, 10);
        if (end && *end == ':') g_pulse_start  = (int)std::strtol(end + 1, &end, 10);
        if (end && *end == ':') g_pulse_count  = (int)std::strtol(end + 1, nullptr, 10);
        std::fprintf(stderr, "[probe] input pulse: btn=%04x period=%d duty=%d start=%d count=%d\n",
                     g_pulse_buttons, g_pulse_period, g_pulse_duty, g_pulse_start, g_pulse_count);
    }
    cfg.input_callbacks.poll_input = input_poll_stub;
    cfg.input_callbacks.get_input = input_get_input;
    cfg.input_callbacks.get_connected_device_info = input_device_info;
    std::fprintf(stderr, "[probe] input: controller0 connected (default), buttons=%04x\n", g_held_buttons);

    // Audio epic #53 (PR 1 of 3): populate the host audio sink. ultramodern
    // reads cfg.audio_callbacks inside recomp::start (recomp.cpp:743), before
    // preinit (recomp.cpp:809) calls init_audio() -> set_audio_frequency(48000).
    // Opening the SDL device now means the runtime's first set_frequency call
    // hits a live queue; the per-game osAiSetNextBuffer_recomp calls later
    // (recomp/funcs_8.c lines 2186, 2828, 3755, 3764, 4075) route the AI buffer
    // into SDL via ultramodern's shim.
    aero::audio::init(48000);
    aero::audio::get_callbacks(&cfg.audio_callbacks);
    std::fprintf(stderr, "[probe] audio: callbacks wired (queue_samples/get_frames_remaining/set_frequency)\n");

    std::fprintf(stderr, "[probe] calling recomp::start\n");
    recomp::start(cfg);
    // Reached only via the watchdog quit path (a boot stall before the VI cap): the VI-cap
    // path exits from vi_cb via boot_summary_and_exit() and never returns here.
    boot_summary_and_exit();
}
