#!/usr/bin/env python3
"""Repository hook: block edits to generated files.

aerogauge.us.toml / aerogauge.syms.toml are outputs of scripts/gen_syms_toml.py
(hand edits are silently dropped on the next regen — a repeated past failure),
and RecompiledFuncs/ + src/aspMain.cpp are ROM-derived recompiler output.

Wired into the repository's local hook configuration. Exit 2 blocks the
operation and explains which hand-written input should be changed instead.
"""
import json
import sys
from pathlib import PurePath

GENERATED_BASENAMES = {"aerogauge.us.toml", "aerogauge.syms.toml"}
GENERATED_PARTS = {"RecompiledFuncs"}
GENERATED_PATHS = {("src", "aspMain.cpp")}


def main():
    try:
        payload = json.load(sys.stdin)
    except Exception:
        return 0
    path = (payload.get("tool_input") or {}).get("file_path") or ""
    if not path:
        return 0
    p = PurePath(path)
    if p.name in GENERATED_BASENAMES:
        print(
            f"BLOCKED: {p.name} is generator output -- hand edits are silently "
            "dropped on the next regen. Edit scripts/gen_syms_toml.py "
            "(LIBULTRA_NAMES / HOOK_NAMES / PATCH_BLOCKS / INDIRECT_STARTS) "
            "instead, then run `python scripts/gen_syms_toml.py` and rebuild. "
            "See BUILDING.md and CONTRIBUTING.md.",
            file=sys.stderr,
        )
        return 2
    if (any(part in GENERATED_PARTS for part in p.parts)
            or tuple(p.parts[-2:]) in GENERATED_PATHS):
        print(
            f"BLOCKED: {path} is ROM-derived recompiler output (regenerated by "
            "BUILDING.md step 3) -- never hand-edit or commit it. To change how "
            "a function is handled, change the generator inputs and regenerate.",
            file=sys.stderr,
        )
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
